import {
  faArrowDown,
  faArrowLeft,
  faArrowRightFromBracket,
  faArrowRotateLeft,
  faArrowUpFromBracket,
  faArrowUpRightFromSquare,
  faBackward,
  faBackwardStep,
  faBars,
  faBell,
  faBook,
  faCheck,
  faChevronDown,
  faChevronUp,
  faCompass as faCompassSolid,
  faCrosshairs,
  faDownload,
  faDrum,
  faEye,
  faEyeSlash,
  faFilm,
  faFilter,
  faFont,
  faForward,
  faForwardStep,
  faGuitar,
  faHeadphones,
  faHeart,
  faIcons,
  faInfo,
  faLink,
  faLocationDot,
  faMap as faMapSolid,
  faMicrophone,
  faMinus,
  faMusic,
  faPen,
  faPlus,
  faQuestion,
  faRoute,
  faSortDown,
  faSortUp,
  faSpinner,
  faStar,
  faTrashCan,
  faVolumeHigh,
  faVolumeOff,
  faVolumeXmark,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

import {
  faCirclePause,
  faCirclePlay,
  faCompass,
  faFileLines,
  faImage,
  faMap,
  faNoteSticky,
} from "@fortawesome/free-regular-svg-icons";

// faEar (pro) → faHeadphones (free solid)
// faEarDeaf (pro) → faVolumeOff (free solid)

export {
  faArrowDown,
  faArrowLeft,
  faArrowRightFromBracket,
  faArrowRotateLeft,
  faArrowUpFromBracket,
  faArrowUpRightFromSquare,
  faBackward,
  faBackwardStep,
  faBars,
  faBell,
  faBook,
  faCheck,
  faChevronDown,
  faChevronUp,
  faCompass,
  faCrosshairs,
  faDownload,
  faDrum,
  faEye,
  faEyeSlash,
  faFilm,
  faFilter,
  faFont,
  faForward,
  faForwardStep,
  faGuitar,
  faHeadphones,
  faHeart,
  faIcons,
  faInfo,
  faLink,
  faLocationDot,
  faMap,
  faMicrophone,
  faMinus,
  faMusic,
  faPen,
  faPlus,
  faQuestion,
  faRoute,
  faSortDown,
  faSortUp,
  faSpinner,
  faStar,
  faTrashCan,
  faVolumeHigh,
  faVolumeOff,
  faVolumeXmark,
  faXmark,
  // Regular icons
  faCirclePause,
  faCirclePlay,
  faFileLines,
  faImage,
  faNoteSticky,
};