import {
  faArrowDown,
  faArrowLeft,
  faArrowRightFromBracket,
  faArrowUpRightFromSquare,
  faBackward,
  faCrosshairs,
  faDrum,
  faEye,
  faEyeSlash,
  faFilter,
  faForward,
  faGuitar,
  faLocationDot,
  faPen,
  faPlus,
  faQuestion,
  faRoute,
  faSortDown,
  faSortUp,
  faStar,
  faTrashCan,
  faVolumeHigh,
  faVolumeXmark,
  faXmark,
  faHeadphones,
  faVolumeOff,
} from "@fortawesome/free-solid-svg-icons";

// faEar (pro) → faHeadphones (free solid)
// faEarDeaf (pro) → faVolumeOff (free solid)

export {
  faArrowDown,
  faArrowLeft,
  faArrowRightFromBracket,
  faArrowUpRightFromSquare,
  faBackward,
  faCrosshairs,
  faDrum,
  faHeadphones,
  faVolumeOff,
  faEye,
  faEyeSlash,
  faFilter,
  faForward,
  faGuitar,
  faLocationDot,
  faPen,
  faPlus,
  faQuestion,
  faRoute,
  faSortDown,
  faSortUp,
  faStar,
  faTrashCan,
  faVolumeHigh,
  faVolumeXmark,
  faXmark,
};
